name: Deploy Redirect to GitHub Pages

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create redirect page
        run: |
          mkdir -p ./redirect-build
          cat > ./redirect-build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Redirecting...</title>
              <meta http-equiv="refresh" content="0; url=https://projects.lbor.dev/uk-weather-analytics-dashboard/">
              <link rel="canonical" href="https://projects.lbor.dev/uk-weather-analytics-dashboard/">
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 50px;
                      background-color: #f5f5f5;
                  }
                  .redirect-message {
                      background: white;
                      padding: 30px;
                      border-radius: 8px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                      max-width: 500px;
                      margin: 0 auto;
                  }
                  .spinner {
                      border: 4px solid #f3f3f3;
                      border-top: 4px solid #3498db;
                      border-radius: 50%;
                      width: 40px;
                      height: 40px;
                      animation: spin 2s linear infinite;
                      margin: 20px auto;
                  }
                  @keyframes spin {
                      0% { transform: rotate(0deg); }
                      100% { transform: rotate(360deg); }
                  }
                  a {
                      color: #3498db;
                      text-decoration: none;
                  }
                  a:hover {
                      text-decoration: underline;
                  }
              </style>
          </head>
          <body>
              <div class="redirect-message">
                  <h1>Site Moved</h1>
                  <div class="spinner"></div>
                  <p>The UK Weather Analytics Dashboard has moved to a new location.</p>
                  <p>You will be automatically redirected in a moment...</p>
                  <p>If you are not redirected automatically, please <a href="https://projects.lbor.dev/uk-weather-analytics-dashboard/">click here</a>.</p>
              </div>

              <script>
                  // JavaScript redirect as backup
                  setTimeout(function() {
                      window.location.href = "https://projects.lbor.dev/uk-weather-analytics-dashboard/";
                  }, 3000);
              </script>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './redirect-build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
